name: publish

on: [push]

jobs:
  publish-image:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Devcontainer Image
        run: |
          docker build -f Dockerfile \
            --tag ghcr.io/optiop/grafana-scenes-image:latest .
          docker push ghcr.io/optiop/grafana-scenes-image:latest